const elements = [{
        "atomicNumber": 1,
        "symbol": "H",
        "name": "Hydrogen",
        "atomicMass": "1.008",
        "category": "nonmetal",
        "group": 1,
        "period": 1,
        "x": 1,
        "y": 1,
        "phase": "Gas",
        "electronConfiguration": "1s1",
        "discovered": "1766",
        "discoveredBy": "Henry Cavendish",
        "isotopes": "¹H (Protium), ²H (Deuterium), ³H (Tritium)",
        "fact": "Hydrogen is the most abundant element in the universe, making up about 75% of its elemental mass."
    },
    {
        "atomicNumber": 2,
        "symbol": "He",
        "name": "Helium",
        "atomicMass": "4.0026",
        "category": "noble-gas",
        "group": 18,
        "period": 1,
        "x": 18,
        "y": 1,
        "phase": "Gas",
        "electronConfiguration": "1s2",
        "discovered": "1868",
        "discoveredBy": "Pierre Janssen, Norman Lockyer",
        "isotopes": "³He, ⁴He",
        "fact": "Helium was first detected in the sun's spectrum before being found on Earth, which is why it's named after Helios, the Greek sun god."
    },
    {
        "atomicNumber": 3,
        "symbol": "Li",
        "name": "Lithium",
        "atomicMass": "6.94",
        "category": "alkali-metal",
        "group": 1,
        "period": 2,
        "x": 1,
        "y": 2,
        "phase": "Solid",
        "electronConfiguration": "[He] 2s1",
        "discovered": "1817",
        "discoveredBy": "Johan August Arfwedson",
        "isotopes": "⁶Li, ⁷Li",
        "fact": "Lithium is the lightest metal and the least dense solid element."
    },
    {
        "atomicNumber": 4,
        "symbol": "Be",
        "name": "Beryllium",
        "atomicMass": "9.0122",
        "category": "alkaline-earth-metal",
        "group": 2,
        "period": 2,
        "x": 2,
        "y": 2,
        "phase": "Solid",
        "electronConfiguration": "[He] 2s2",
        "discovered": "1798",
        "discoveredBy": "Louis-Nicolas Vauquelin",
        "isotopes": "⁹Be",
        "fact": "Beryllium is used in aerospace components due to its high strength-to-weight ratio."
    },
    {
        "atomicNumber": 5,
        "symbol": "B",
        "name": "Boron",
        "atomicMass": "10.81",
        "category": "metalloid",
        "group": 13,
        "period": 2,
        "x": 13,
        "y": 2,
        "phase": "Solid",
        "electronConfiguration": "[He] 2s2 2p1",
        "discovered": "1808",
        "discoveredBy": "Sir Humphry Davy, Joseph Louis Gay-Lussac, Louis Jacques Thénard",
        "isotopes": "⁵B, ⁶B, ⁷B",
        "fact": "Boron is essential for plant growth and is used in glass and ceramics."
    },
    {
        "atomicNumber": 6,
        "symbol": "C",
        "name": "Carbon",
        "atomicMass": "12.011",
        "category": "nonmetal",
        "group": 14,
        "period": 2,
        "x": 14,
        "y": 2,
        "phase": "Solid",
        "electronConfiguration": "[He] 2s2 2p2",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "¹²C, ¹³C, ¹⁴C",
        "fact": "Carbon is the basis of all known life on Earth and can form a vast number of compounds."
    },
    {
        "atomicNumber": 7,
        "symbol": "N",
        "name": "Nitrogen",
        "atomicMass": "14.007",
        "category": "nonmetal",
        "group": 15,
        "period": 2,
        "x": 15,
        "y": 2,
        "phase": "Gas",
        "electronConfiguration": "[He] 2s2 2p3",
        "discovered": "1772",
        "discoveredBy": "Daniel Rutherford",
        "isotopes": "¹⁴N, ¹⁵N",
        "fact": "Nitrogen makes up about 78% of the Earth's atmosphere."
    },
    {
        "atomicNumber": 8,
        "symbol": "O",
        "name": "Oxygen",
        "atomicMass": "15.999",
        "category": "nonmetal",
        "group": 16,
        "period": 2,
        "x": 16,
        "y": 2,
        "phase": "Gas",
        "electronConfiguration": "[He] 2s2 2p4",
        "discovered": "1774",
        "discoveredBy": "Joseph Priestley, Carl Wilhelm Scheele",
        "isotopes": "¹⁶O, ¹⁷O, ¹⁸O",
        "fact": "Oxygen is essential for respiration in most living organisms."
    },
    {
        "atomicNumber": 9,
        "symbol": "F",
        "name": "Fluorine",
        "atomicMass": "18.998",
        "category": "nonmetal",
        "group": 17,
        "period": 2,
        "x": 17,
        "y": 2,
        "phase": "Gas",
        "electronConfiguration": "[He] 2s2 2p5",
        "discovered": "1886",
        "discoveredBy": "Henri Moissan",
        "isotopes": "¹⁹F",
        "fact": "Fluorine is the most electronegative and reactive of all elements."
    },
    {
        "atomicNumber": 10,
        "symbol": "Ne",
        "name": "Neon",
        "atomicMass": "20.180",
        "category": "noble-gas",
        "group": 18,
        "period": 2,
        "x": 18,
        "y": 2,
        "phase": "Gas",
        "electronConfiguration": "[He] 2s2 2p6",
        "discovered": "1898",
        "discoveredBy": "William Ramsay, Morris Travers",
        "isotopes": "²⁰Ne, ²¹Ne, ²²Ne",
        "fact": "Neon is used in neon signs and is known for its bright colors."
    },
    {
        "atomicNumber": 11,
        "symbol": "Na",
        "name": "Sodium",
        "atomicMass": "22.990",
        "category": "alkali-metal",
        "group": 1,
        "period": 3,
        "x": 1,
        "y": 3,
        "phase": "Solid",
        "electronConfiguration": "[Ne] 3s1",
        "discovered": "1807",
        "discoveredBy": "Sir Humphry Davy",
        "isotopes": "²³Na",
        "fact": "Sodium is essential for life and is commonly found in table salt."
    },
    {
        "atomicNumber": 12,
        "symbol": "Mg",
        "name": "Magnesium",
        "atomicMass": "24.305",
        "category": "alkaline-earth-metal",
        "group": 2,
        "period": 3,
        "x": 2,
        "y": 3,
        "phase": "Solid",
        "electronConfiguration": "[Ne] 3s2",
        "discovered": "1755",
        "discoveredBy": "Joseph Black",
        "isotopes": "²⁴Mg, ²⁵Mg, ²⁶Mg",
        "fact": "Magnesium is important for many biological functions and is used in fireworks."
    },
    {
        "atomicNumber": 13,
        "symbol": "Al",
        "name": "Aluminum",
        "atomicMass": "26.982",
        "category": "post-transition-metal",
        "group": 13,
        "period": 3,
        "x": 13,
        "y": 3,
        "phase": "Solid",
        "electronConfiguration": "[Ne] 3s2 3p1",
        "discovered": "1825",
        "discoveredBy": "Hans Christian Ørsted",
        "isotopes": "²⁶Al, ²⁷Al",
        "fact": "Aluminum is the most abundant metal in the Earth's crust and is used in a wide range of applications."
    },
    {
        "atomicNumber": 14,
        "symbol": "Si",
        "name": "Silicon",
        "atomicMass": "28.085",
        "category": "metalloid",
        "group": 14,
        "period": 3,
        "x": 14,
        "y": 3,
        "phase": "Solid",
        "electronConfiguration": "[Ne] 3s2 3p2",
        "discovered": "1824",
        "discoveredBy": "Jöns Jacob Berzelius",
        "isotopes": "²⁸Si, ²⁹Si, ³⁰Si",
        "fact": "Silicon is a key component in semiconductors and is widely used in electronics."
    },

    {
        "atomicNumber": 15,
        "symbol": "P",
        "name": "Phosphorus",
        "atomicMass": "30.974",
        "category": "nonmetal",
        "group": 15,
        "period": 3,
        "x": 15,
        "y": 3,
        "phase": "Solid",
        "electronConfiguration": "[Ne] 3s2 3p3",
        "discovered": "1669",
        "discoveredBy": "Hennig Brand",
        "isotopes": "³¹P",
        "fact": "Phosphorus is essential for life and is a key component of DNA and ATP."
    },
    {
        "atomicNumber": 16,
        "symbol": "S",
        "name": "Sulfur",
        "atomicMass": "32.06",
        "category": "nonmetal",
        "group": 16,
        "period": 3,
        "x": 16,
        "y": 3,
        "phase": "Solid",
        "electronConfiguration": "[Ne] 3s2 3p4",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "³²S, ³³S, ³⁴S, ³⁶S",
        "fact": "Sulfur is known for its distinct yellow color and is used in fertilizers and gunpowder."
    },
    {
        "atomicNumber": 17,
        "symbol": "Cl",
        "name": "Chlorine",
        "atomicMass": "35.45",
        "category": "nonmetal",
        "group": 17,
        "period": 3,
        "x": 17,
        "y": 3,
        "phase": "Gas",
        "electronConfiguration": "[Ne] 3s2 3p5",
        "discovered": "1774",
        "discoveredBy": "Carl Wilhelm Scheele",
        "isotopes": "³⁵Cl, ³⁷Cl",
        "fact": "Chlorine is widely used for water purification and in the production of various chemicals."
    },
    {
        "atomicNumber": 18,
        "symbol": "Ar",
        "name": "Argon",
        "atomicMass": "39.948",
        "category": "noble-gas",
        "group": 18,
        "period": 3,
        "x": 18,
        "y": 3,
        "phase": "Gas",
        "electronConfiguration": "[Ne] 3s2 3p6",
        "discovered": "1894",
        "discoveredBy": "Lord Rayleigh, William Ramsay",
        "isotopes": "³⁸Ar, ³⁹Ar, ⁴⁰Ar",
        "fact": "Argon is used in light bulbs and as an inert gas shield for welding."
    },
    {
        "atomicNumber": 19,
        "symbol": "K",
        "name": "Potassium",
        "atomicMass": "39.098",
        "category": "alkali-metal",
        "group": 1,
        "period": 4,
        "x": 1,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 4s1",
        "discovered": "1807",
        "discoveredBy": "Sir Humphry Davy",
        "isotopes": "³⁹K, ⁴¹K",
        "fact": "Potassium is essential for plant growth and is a key component of fertilizers."
    },
    {
        "atomicNumber": 20,
        "symbol": "Ca",
        "name": "Calcium",
        "atomicMass": "40.078",
        "category": "alkaline-earth-metal",
        "group": 2,
        "period": 4,
        "x": 2,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 4s2",
        "discovered": "1808",
        "discoveredBy": "Sir Humphry Davy",
        "isotopes": "⁴⁰Ca, ⁴²Ca, ⁴³Ca, ⁴⁴Ca, ⁴⁶Ca, ⁴⁸Ca",
        "fact": "Calcium is essential for living organisms, particularly in cell physiology."
    },

    {
        "atomicNumber": 21,
        "symbol": "Sc",
        "name": "Scandium",
        "atomicMass": "44.956",
        "category": "transition-metal",
        "group": 3,
        "period": 4,
        "x": 3,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d1 4s2",
        "discovered": "1879",
        "discoveredBy": "Lars Fredrik Nilson",
        "isotopes": "⁴⁵Sc",
        "fact": "Scandium is used in aerospace components and sports equipment due to its light weight and strength."
    },
    {
        "atomicNumber": 22,
        "symbol": "Ti",
        "name": "Titanium",
        "atomicMass": "47.867",
        "category": "transition-metal",
        "group": 4,
        "period": 4,
        "x": 4,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d2 4s2",
        "discovered": "1791",
        "discoveredBy": "William Gregor",
        "isotopes": "⁴⁶Ti, ⁴⁷Ti, ⁴⁸Ti, ⁴⁹Ti, ⁵⁰Ti",
        "fact": "Titanium is known for its high strength, low density, and resistance to corrosion."
    },
    {
        "atomicNumber": 23,
        "symbol": "V",
        "name": "Vanadium",
        "atomicMass": "50.942",
        "category": "transition-metal",
        "group": 5,
        "period": 4,
        "x": 5,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d3 4s2",
        "discovered": "1801",
        "discoveredBy": "Andrés Manuel del Río",
        "isotopes": "⁵⁰V, ⁵¹V",
        "fact": "Vanadium is used to produce strong, corrosion-resistant steel alloys."
    },
    {
        "atomicNumber": 24,
        "symbol": "Cr",
        "name": "Chromium",
        "atomicMass": "51.996",
        "category": "transition-metal",
        "group": 6,
        "period": 4,
        "x": 6,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d5 4s1",
        "discovered": "1797",
        "discoveredBy": "Louis Nicolas Vauquelin",
        "isotopes": "⁵⁰Cr, ⁵²Cr, ⁵³Cr, ⁵⁴Cr",
        "fact": "Chromium is used to make stainless steel and gives rubies their red color."
    },

    {
        "atomicNumber": 25,
        "symbol": "Mn",
        "name": "Manganese",
        "atomicMass": "54.938",
        "category": "transition-metal",
        "group": 7,
        "period": 4,
        "x": 7,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d5 4s2",
        "discovered": "1774",
        "discoveredBy": "Johann Gottlieb Gahn",
        "isotopes": "⁵⁴Mn, ⁵⁵Mn, ⁵⁶Mn, ⁵⁷Mn, ⁵⁸Mn",
        "fact": "Manganese is essential for the functioning of enzymes in the body."
    },
    {
        "atomicNumber": 26,
        "symbol": "Fe",
        "name": "Iron",
        "atomicMass": "55.845",
        "category": "transition-metal",
        "group": 8,
        "period": 4,
        "x": 8,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d6 4s2",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "⁵⁴Fe, ⁵⁶Fe, ⁵⁷Fe, ⁵⁸Fe",
        "fact": "Iron is the most common element (by mass) forming the Earth, and it's crucial for hemoglobin in blood."
    },
    {
        "atomicNumber": 27,
        "symbol": "Co",
        "name": "Cobalt",
        "atomicMass": "58.933",
        "category": "transition-metal",
        "group": 9,
        "period": 4,
        "x": 9,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d7 4s2",
        "discovered": "1735",
        "discoveredBy": "Georg Brandt",
        "isotopes": "⁵⁷Co, ⁵⁸Co, ⁵⁹Co, ⁶⁰Co",
        "fact": "Cobalt is used in the production of high-strength alloys and batteries."
    },
    {
        "atomicNumber": 28,
        "symbol": "Ni",
        "name": "Nickel",
        "atomicMass": "58.693",
        "category": "transition-metal",
        "group": 10,
        "period": 4,
        "x": 10,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d8 4s2",
        "discovered": "1751",
        "discoveredBy": "Axel Fredrik Cronstedt",
        "isotopes": "⁵⁸Ni, ⁵⁹Ni, ⁶⁰Ni, ⁶¹Ni, ⁶²Ni",
        "fact": "Nickel is used in coins, batteries, and as a catalyst in hydrogenation."
    },
    {
        "atomicNumber": 29,
        "symbol": "Cu",
        "name": "Copper",
        "atomicMass": "63.546",
        "category": "transition-metal",
        "group": 11,
        "period": 4,
        "x": 11,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d10 4s1",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "⁶⁰Cu, ⁶¹Cu, ⁶²Cu, ⁶³Cu, ⁶⁴Cu",
        "fact": "Copper is an excellent conductor of electricity and is widely used in electrical wiring."
    },
    {
        "atomicNumber": 30,
        "symbol": "Zn",
        "name": "Zinc",
        "atomicMass": "65.38",
        "category": "transition-metal",
        "group": 12,
        "period": 4,
        "x": 12,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d10 4s2",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "⁶⁴Zn, ⁶⁵Zn, ⁶⁶Zn, ⁶⁷Zn, ⁶⁸Zn",
        "fact": "Zinc is essential for human health and is used in galvanization to protect iron from rusting."
    }, {
        "atomicNumber": 31,
        "symbol": "Ga",
        "name": "Gallium",
        "atomicMass": "69.723",
        "category": "post-transition-metal",
        "group": 13,
        "period": 4,
        "x": 13,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d10 4s2 4p1",
        "discovered": "1875",
        "discoveredBy": "Paul-Émile Lecoq de Boisbaudran",
        "isotopes": "⁶⁹Ga, ⁷¹Ga",
        "fact": "Gallium can melt in your hand, as its melting point is just above room temperature."
    },
    {
        "atomicNumber": 32,
        "symbol": "Ge",
        "name": "Germanium",
        "atomicMass": "72.630",
        "category": "metalloid",
        "group": 14,
        "period": 4,
        "x": 14,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d10 4s2 4p2",
        "discovered": "1886",
        "discoveredBy": "Clemens Winkler",
        "isotopes": "⁶⁶Ge, ⁶⁸Ge, ⁶⁹Ge, ⁷⁰Ge",
        "fact": "Germanium is used in semiconductors and fiber optics."
    },
    {
        "atomicNumber": 33,
        "symbol": "As",
        "name": "Arsenic",
        "atomicMass": "74.922",
        "category": "metalloid",
        "group": 15,
        "period": 4,
        "x": 15,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d10 4s2 4p3",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "⁷⁵As",
        "fact": "Arsenic is notorious for its toxicity and has been used as a poison."
    },
    {
        "atomicNumber": 34,
        "symbol": "Se",
        "name": "Selenium",
        "atomicMass": "78.971",
        "category": "nonmetal",
        "group": 16,
        "period": 4,
        "x": 16,
        "y": 4,
        "phase": "Solid",
        "electronConfiguration": "[Ar] 3d10 4s2 4p4",
        "discovered": "1817",
        "discoveredBy": "Jöns Jacob Berzelius, Johan Gottlieb Gahn",
        "isotopes": "⁷⁴Se, ⁷⁶Se, ⁷⁷Se, ⁷⁸Se, ⁷⁹Se, ⁸⁰Se",
        "fact": "Selenium is used in photocopiers and as a dietary supplement."
    },
    {
        "atomicNumber": 35,
        "symbol": "Br",
        "name": "Bromine",
        "atomicMass": "79.904",
        "category": "halogen",
        "group": 17,
        "period": 4,
        "x": 17,
        "y": 4,
        "phase": "Liquid",
        "electronConfiguration": "[Ar] 3d10 4s2 4p5",
        "discovered": "1826",
        "discoveredBy": "Antoine Jérôme Balard",
        "isotopes": "⁷⁸Br, ⁷⁹Br, ⁸¹Br",
        "fact": "Bromine is the only nonmetallic element that is liquid at room temperature."
    },
    {
        "atomicNumber": 36,
        "symbol": "Kr",
        "name": "Krypton",
        "atomicMass": "83.798",
        "category": "noble-gas",
        "group": 18,
        "period": 4,
        "x": 18,
        "y": 4,
        "phase": "Gas",
        "electronConfiguration": "[Ar] 3d10 4s2 4p6",
        "discovered": "1898",
        "discoveredBy": "William Ramsay, Morris Travers",
        "isotopes": "⁸⁴Kr, ⁸⁶Kr, ⁸⁷Kr, ⁸⁸Kr, ⁹⁰Kr",
        "fact": "Krypton is used in high-performance lighting and photography."
    },
    {
        "atomicNumber": 37,
        "symbol": "Rb",
        "name": "Rubidium",
        "atomicMass": "85.467",
        "category": "alkali-metal",
        "group": 1,
        "period": 5,
        "x": 1,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 5s1",
        "discovered": "1861",
        "discoveredBy": "Robert Bunsen, Gustav Kirchhoff",
        "isotopes": "⁸⁵Rb, ⁸⁷Rb",
        "fact": "Rubidium is highly reactive and is used in research and specialty glasses."
    },
    {
        "atomicNumber": 38,
        "symbol": "Sr",
        "name": "Strontium",
        "atomicMass": "87.62",
        "category": "alkaline-earth-metal",
        "group": 2,
        "period": 5,
        "x": 2,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 5s2",
        "discovered": "1790",
        "discoveredBy": "Adair Crawford",
        "isotopes": "⁸⁴Sr, ⁸⁶Sr, ⁸⁷Sr, ⁸⁸Sr",
        "fact": "Strontium is used in fireworks to produce a bright red color."
    },
    {
        "atomicNumber": 39,
        "symbol": "Y",
        "name": "Yttrium",
        "atomicMass": "88.906",
        "category": "transition-metal",
        "group": 3,
        "period": 5,
        "x": 3,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d1 5s2",
        "discovered": "1794",
        "discoveredBy": "Johan Gadolin",
        "isotopes": "⁸⁹Y",
        "fact": "Yttrium is used in LEDs and phosphors for color television tubes."
    },
    {
        "atomicNumber": 40,
        "symbol": "Zr",
        "name": "Zirconium",
        "atomicMass": "91.224",
        "category": "transition-metal",
        "group": 4,
        "period": 5,
        "x": 4,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d2 5s2",
        "discovered": "1789",
        "discoveredBy": "Martin Heinrich Klaproth",
        "isotopes": "⁹⁰Zr, ⁹¹Zr, ⁹²Zr, ⁹⁴Zr, ⁹⁶Zr",
        "fact": "Zirconium is highly resistant to corrosion and is used in nuclear reactors."
    }, {
        "atomicNumber": 41,
        "symbol": "Nb",
        "name": "Niobium",
        "atomicMass": "92.906",
        "category": "transition-metal",
        "group": 5,
        "period": 5,
        "x": 5,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d4 5s1",
        "discovered": "1801",
        "discoveredBy": "Charles Hatchett",
        "isotopes": "⁹²Nb, ⁹³Nb",
        "fact": "Niobium is used in steel production to improve strength and resistance to corrosion."
    },
    {
        "atomicNumber": 42,
        "symbol": "Mo",
        "name": "Molybdenum",
        "atomicMass": "95.95",
        "category": "transition-metal",
        "group": 6,
        "period": 5,
        "x": 6,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d5 5s1",
        "discovered": "1778",
        "discoveredBy": "Carl Wilhelm Scheele",
        "isotopes": "⁹⁸Mo, ⁹⁹Mo, ¹⁰⁰Mo",
        "fact": "Molybdenum is used in high-strength steel alloys and as a catalyst in the petroleum industry."
    },
    {
        "atomicNumber": 43,
        "symbol": "Tc",
        "name": "Technetium",
        "atomicMass": "(98)",
        "category": "transition-metal",
        "group": 7,
        "period": 5,
        "x": 7,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d5 5s2",
        "discovered": "1937",
        "discoveredBy": "Carlo Perrier, Emilio Segrè",
        "isotopes": "⁹⁹Tc",
        "fact": "Technetium is the first artificially produced element and is used in medical imaging."
    },
    {
        "atomicNumber": 44,
        "symbol": "Ru",
        "name": "Ruthenium",
        "atomicMass": "101.07",
        "category": "transition-metal",
        "group": 8,
        "period": 5,
        "x": 8,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d7 5s1",
        "discovered": "1844",
        "discoveredBy": "Karl Ernst Claus",
        "isotopes": "¹⁰²Ru, ¹⁰⁴Ru, ¹⁰⁶Ru",
        "fact": "Ruthenium is used in electrical contacts and as a catalyst in chemical reactions."
    },
    {
        "atomicNumber": 45,
        "symbol": "Rh",
        "name": "Rhodium",
        "atomicMass": "102.91",
        "category": "transition-metal",
        "group": 9,
        "period": 5,
        "x": 9,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d8 5s1",
        "discovered": "1803",
        "discoveredBy": "William Hyde Wollaston",
        "isotopes": "¹⁰⁶Rh, ¹⁰⁸Rh",
        "fact": "Rhodium is highly reflective and is used in catalytic converters and jewelry."
    },
    {
        "atomicNumber": 46,
        "symbol": "Pd",
        "name": "Palladium",
        "atomicMass": "106.42",
        "category": "transition-metal",
        "group": 10,
        "period": 5,
        "x": 10,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d10",
        "discovered": "1803",
        "discoveredBy": "William Hyde Wollaston",
        "isotopes": "¹⁰²Pd, ¹⁰⁴Pd, ¹⁰⁶Pd",
        "fact": "Palladium is used in catalytic converters and in electronics due to its excellent conductivity."
    },
    {
        "atomicNumber": 47,
        "symbol": "Ag",
        "name": "Silver",
        "atomicMass": "107.87",
        "category": "transition-metal",
        "group": 11,
        "period": 5,
        "x": 11,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d10 5s1",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "¹⁰⁷Ag, ¹⁰⁹Ag",
        "fact": "Silver has the highest electrical conductivity of all elements and is used in jewelry, coins, and electronics."
    },
    {
        "atomicNumber": 48,
        "symbol": "Cd",
        "name": "Cadmium",
        "atomicMass": "112.41",
        "category": "transition-metal",
        "group": 12,
        "period": 5,
        "x": 12,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d10 5s2",
        "discovered": "1817",
        "discoveredBy": "Friedrich Stromeyer",
        "isotopes": "¹⁰⁶Cd, ¹⁰⁸Cd, ¹¹⁰Cd, ¹¹¹Cd, ¹¹²Cd, ¹¹³Cd, ¹¹⁴Cd, ¹¹⁶Cd",
        "fact": "Cadmium is used in batteries and pigments but is toxic to humans."
    },
    {
        "atomicNumber": 49,
        "symbol": "In",
        "name": "Indium",
        "atomicMass": "114.82",
        "category": "post-transition-metal",
        "group": 13,
        "period": 5,
        "x": 13,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d10 5s2 5p1",
        "discovered": "1863",
        "discoveredBy": "Ferdinand Reich, Hieronymous Theodor Richter",
        "isotopes": "¹¹³In, ¹¹⁵In",
        "fact": "Indium is used in touchscreens, LCDs, and solders."
    },
    {
        "atomicNumber": 50,
        "symbol": "Sn",
        "name": "Tin",
        "atomicMass": "118.71",
        "category": "post-transition-metal",
        "group": 14,
        "period": 5,
        "x": 14,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d10 5s2 5p2",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "¹¹²Sn, ¹¹⁴Sn, ¹¹⁵Sn, ¹¹⁶Sn, ¹¹⁷Sn, ¹¹⁸Sn, ¹¹⁹Sn, ¹²⁰Sn, ¹²²Sn, ¹²⁴Sn",
        "fact": "Tin is used to coat other metals to prevent corrosion and is a major component of bronze."
    },

    {
        "atomicNumber": 51,
        "symbol": "Sb",
        "name": "Antimony",
        "atomicMass": "121.760",
        "category": "metalloid",
        "group": 15,
        "period": 5,
        "x": 15,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d10 5s2 5p3",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "¹²¹Sb, ¹²³Sb",
        "fact": "Antimony is used in flame retardants and lead-acid batteries."
    },
    {
        "atomicNumber": 52,
        "symbol": "Te",
        "name": "Tellurium",
        "atomicMass": "127.60",
        "category": "metalloid",
        "group": 16,
        "period": 5,
        "x": 16,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d10 5s2 5p4",
        "discovered": "1782",
        "discoveredBy": "Franz-Joseph Müller von Reichenstein",
        "isotopes": "¹²⁶Te, ¹²⁷Te, ¹²⁸Te, ¹²⁹Te, ¹³⁰Te",
        "fact": "Tellurium is used in alloys and as a semiconductor."
    },
    {
        "atomicNumber": 53,
        "symbol": "I",
        "name": "Iodine",
        "atomicMass": "126.904",
        "category": "halogen",
        "group": 17,
        "period": 5,
        "x": 17,
        "y": 5,
        "phase": "Solid",
        "electronConfiguration": "[Kr] 4d10 5s2 5p5",
        "discovered": "1811",
        "discoveredBy": "Bernard Courtois",
        "isotopes": "¹²⁷I",
        "fact": "Iodine is essential for thyroid function and is used as a disinfectant."
    },
    {
        "atomicNumber": 54,
        "symbol": "Xe",
        "name": "Xenon",
        "atomicMass": "131.293",
        "category": "noble-gas",
        "group": 18,
        "period": 5,
        "x": 18,
        "y": 5,
        "phase": "Gas",
        "electronConfiguration": "[Kr] 4d10 5s2 5p6",
        "discovered": "1898",
        "discoveredBy": "William Ramsay, Morris Travers",
        "isotopes": "¹²⁴Xe, ¹²⁶Xe, ¹²⁸Xe, ¹²⁹Xe, ¹³⁰Xe, ¹³¹Xe, ¹³²Xe, ¹³⁴Xe, ¹³⁶Xe",
        "fact": "Xenon is used in flash lamps and ion propulsion systems for spacecraft."
    },
    {
        "atomicNumber": 55,
        "symbol": "Cs",
        "name": "Cesium",
        "atomicMass": "132.905",
        "category": "alkali-metal",
        "group": 1,
        "period": 6,
        "x": 1,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 6s1",
        "discovered": "1860",
        "discoveredBy": "Robert Bunsen, Gustav Kirchhoff",
        "isotopes": "¹³³Cs",
        "fact": "Cesium is used in atomic clocks and is highly reactive with water."
    },
    {
        "atomicNumber": 56,
        "symbol": "Ba",
        "name": "Barium",
        "atomicMass": "137.327",
        "category": "alkaline-earth-metal",
        "group": 2,
        "period": 6,
        "x": 2,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 6s2",
        "discovered": "1808",
        "discoveredBy": "Sir Humphry Davy",
        "isotopes": "¹³⁰Ba, ¹³²Ba, ¹³⁴Ba, ¹³⁵Ba, ¹³⁶Ba, ¹³⁷Ba, ¹³⁸Ba",
        "fact": "Barium compounds are used in medical imaging of the digestive system."
    },
    {
        "atomicNumber": 57,
        "symbol": "La",
        "name": "Lanthanum",
        "atomicMass": "138.905",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 3,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 5d1 6s2",
        "discovered": "1839",
        "discoveredBy": "Carl Gustaf Mosander",
        "isotopes": "¹³⁸La, ¹³⁹La",
        "fact": "Lanthanum is used in camera and telescope lenses."
    },
    {
        "atomicNumber": 58,
        "symbol": "Ce",
        "name": "Cerium",
        "atomicMass": "140.116",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 4,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f1 5d1 6s2",
        "discovered": "1803",
        "discoveredBy": "Jöns Jacob Berzelius, Wilhelm Hisinger, Martin Heinrich Klaproth",
        "isotopes": "¹³⁶Ce, ¹³⁸Ce, ¹⁴⁰Ce, ¹⁴²Ce",
        "fact": "Cerium is used in catalytic converters and glass polishing powders."
    },
    {
        "atomicNumber": 59,
        "symbol": "Pr",
        "name": "Praseodymium",
        "atomicMass": "140.907",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 5,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f3 6s2",
        "discovered": "1885",
        "discoveredBy": "Carl Auer von Welsbach",
        "isotopes": "¹⁴¹Pr",
        "fact": "Praseodymium is used to color glass and ceramics."
    },
    {
        "atomicNumber": 60,
        "symbol": "Nd",
        "name": "Neodymium",
        "atomicMass": "144.242",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 6,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f4 6s2",
        "discovered": "1885",
        "discoveredBy": "Carl Auer von Welsbach",
        "isotopes": "¹⁴²Nd, ¹⁴³Nd, ¹⁴⁴Nd, ¹⁴⁵Nd, ¹⁴⁶Nd, ¹⁴⁸Nd, ¹⁵⁰Nd",
        "fact": "Neodymium is used in powerful magnets found in headphones and microphones."
    }, {
        "atomicNumber": 61,
        "symbol": "Pm",
        "name": "Promethium",
        "atomicMass": "(145)",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 7,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f5 6s2",
        "discovered": "1945",
        "discoveredBy": "Jacob A. Marinsky, Lawrence E. Glendenin, Charles D. Coryell",
        "isotopes": "¹⁴⁵Pm (no stable isotopes)",
        "fact": "Promethium is radioactive and is used in luminous paint and atomic batteries."
    },
    {
        "atomicNumber": 62,
        "symbol": "Sm",
        "name": "Samarium",
        "atomicMass": "150.36",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 8,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f6 6s2",
        "discovered": "1879",
        "discoveredBy": "Paul-Émile Lecoq de Boisbaudran",
        "isotopes": "¹⁴⁴Sm, ¹⁴⁷Sm, ¹⁴⁸Sm, ¹⁴⁹Sm, ¹⁵⁰Sm, ¹⁵²Sm, ¹⁵⁴Sm",
        "fact": "Samarium is used in powerful magnets and in cancer treatment."
    },
    {
        "atomicNumber": 63,
        "symbol": "Eu",
        "name": "Europium",
        "atomicMass": "151.964",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 9,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f7 6s2",
        "discovered": "1901",
        "discoveredBy": "Eugène-Anatole Demarçay",
        "isotopes": "¹⁵¹Eu, ¹⁵³Eu",
        "fact": "Europium is used in phosphorescent and fluorescent applications, such as in TV screens."
    },
    {
        "atomicNumber": 64,
        "symbol": "Gd",
        "name": "Gadolinium",
        "atomicMass": "157.25",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 10,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f7 5d1 6s2",
        "discovered": "1880",
        "discoveredBy": "Jean Charles Galissard de Marignac",
        "isotopes": "¹⁵²Gd, ¹⁵⁴Gd, ¹⁵⁵Gd, ¹⁵⁶Gd, ¹⁵⁷Gd, ¹⁵⁸Gd, ¹⁶⁰Gd",
        "fact": "Gadolinium is used as a contrast agent in MRI scans."
    },
    {
        "atomicNumber": 65,
        "symbol": "Tb",
        "name": "Terbium",
        "atomicMass": "158.925",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 11,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f9 6s2",
        "discovered": "1843",
        "discoveredBy": "Carl Gustaf Mosander",
        "isotopes": "¹⁵⁹Tb",
        "fact": "Terbium is used in green phosphors for color TV tubes and LEDs."
    },
    {
        "atomicNumber": 66,
        "symbol": "Dy",
        "name": "Dysprosium",
        "atomicMass": "162.500",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 12,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f10 6s2",
        "discovered": "1886",
        "discoveredBy": "Paul-Émile Lecoq de Boisbaudran",
        "isotopes": "¹⁵⁶Dy, ¹⁵⁸Dy, ¹⁶⁰Dy, ¹⁶¹Dy, ¹⁶²Dy, ¹⁶³Dy, ¹⁶⁴Dy",
        "fact": "Dysprosium is used in magnets and nuclear reactor control rods."
    },
    {
        "atomicNumber": 67,
        "symbol": "Ho",
        "name": "Holmium",
        "atomicMass": "164.930",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 13,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f11 6s2",
        "discovered": "1878",
        "discoveredBy": "Per Teodor Cleve",
        "isotopes": "¹⁶⁵Ho",
        "fact": "Holmium has the highest magnetic strength of any element."
    },
    {
        "atomicNumber": 68,
        "symbol": "Er",
        "name": "Erbium",
        "atomicMass": "167.259",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 14,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f12 6s2",
        "discovered": "1842",
        "discoveredBy": "Carl Gustaf Mosander",
        "isotopes": "¹⁶²Er, ¹⁶⁴Er, ¹⁶⁶Er, ¹⁶⁷Er, ¹⁶⁸Er, ¹⁷⁰Er",
        "fact": "Erbium is used in fiber optic communications and lasers."
    },
    {
        "atomicNumber": 69,
        "symbol": "Tm",
        "name": "Thulium",
        "atomicMass": "168.934",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 15,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f13 6s2",
        "discovered": "1879",
        "discoveredBy": "Per Teodor Cleve",
        "isotopes": "¹⁶⁹Tm",
        "fact": "Thulium is used in portable X-ray machines and lasers."
    },
    {
        "atomicNumber": 70,
        "symbol": "Yb",
        "name": "Ytterbium",
        "atomicMass": "173.05",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 16,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 6s2",
        "discovered": "1878",
        "discoveredBy": "Jean Charles Galissard de Marignac",
        "isotopes": "¹⁶⁸Yb, ¹⁷⁰Yb, ¹⁷¹Yb, ¹⁷²Yb, ¹⁷³Yb, ¹⁷⁴Yb, ¹⁷⁶Yb",
        "fact": "Ytterbium is used in atomic clocks and has the highest electrical resistance of all metals when under stress."
    },
    {
        "atomicNumber": 71,
        "symbol": "Lu",
        "name": "Lutetium",
        "atomicMass": "174.97",
        "category": "lanthanide",
        "group": null,
        "period": 6,
        "x": 17,
        "y": 9,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d1 6s2",
        "discovered": "1907",
        "discoveredBy": "Georges Urbain and Carl Auer von Welsbach",
        "isotopes": "¹⁷⁵Lu, ¹⁷⁶Lu",
        "fact": "Lutetium is the hardest and densest of the lanthanides and is used in petroleum refining."
    },
    {
        "atomicNumber": 72,
        "symbol": "Hf",
        "name": "Hafnium",
        "atomicMass": "178.49",
        "category": "transition-metal",
        "group": 4,
        "period": 6,
        "x": 4,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d2 6s2",
        "discovered": "1923",
        "discoveredBy": "Dirk Coster and George de Hevesy",
        "isotopes": "¹⁷⁴Hf, ¹⁷⁶Hf, ¹⁷⁷Hf, ¹⁷⁸Hf, ¹⁷⁹Hf, ¹⁸⁰Hf",
        "fact": "Hafnium is used in nuclear reactor control rods because it absorbs neutrons well."
    },
    {
        "atomicNumber": 73,
        "symbol": "Ta",
        "name": "Tantalum",
        "atomicMass": "180.95",
        "category": "transition-metal",
        "group": 5,
        "period": 6,
        "x": 5,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d3 6s2",
        "discovered": "1802",
        "discoveredBy": "Anders Gustaf Ekeberg",
        "isotopes": "¹⁸⁰Ta, ¹⁸¹Ta",
        "fact": "Tantalum is highly corrosion-resistant and is used in surgical implants and electronics."
    },
    {
        "atomicNumber": 74,
        "symbol": "W",
        "name": "Tungsten",
        "atomicMass": "183.84",
        "category": "transition-metal",
        "group": 6,
        "period": 6,
        "x": 6,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d4 6s2",
        "discovered": "1783",
        "discoveredBy": "Juan José and Fausto Elhuyar",
        "isotopes": "¹⁸²W, ¹⁸³W, ¹⁸⁴W, ¹⁸⁶W",
        "fact": "Tungsten has the highest melting point of all metals (3,422°C or 6,192°F)."
    },
    {
        "atomicNumber": 75,
        "symbol": "Re",
        "name": "Rhenium",
        "atomicMass": "186.21",
        "category": "transition-metal",
        "group": 7,
        "period": 6,
        "x": 7,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d5 6s2",
        "discovered": "1925",
        "discoveredBy": "Walter Noddack, Ida Tacke, and Otto Berg",
        "isotopes": "¹⁸⁵Re, ¹⁸⁷Re",
        "fact": "Rhenium was the last naturally occurring element to be discovered and has the highest boiling point of any element."
    },
    {
        "atomicNumber": 76,
        "symbol": "Os",
        "name": "Osmium",
        "atomicMass": "190.23",
        "category": "transition-metal",
        "group": 8,
        "period": 6,
        "x": 8,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d6 6s2",
        "discovered": "1803",
        "discoveredBy": "Smithson Tennant",
        "isotopes": "¹⁸⁴Os, ¹⁸⁶Os, ¹⁸⁷Os, ¹⁸⁸Os, ¹⁸⁹Os, ¹⁹⁰Os, ¹⁹²Os",
        "fact": "Osmium is the densest naturally occurring element (22.59 g/cm³) and is used in fountain pen tips."
    },
    {
        "atomicNumber": 77,
        "symbol": "Ir",
        "name": "Iridium",
        "atomicMass": "192.22",
        "category": "transition-metal",
        "group": 9,
        "period": 6,
        "x": 9,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d7 6s2",
        "discovered": "1803",
        "discoveredBy": "Smithson Tennant",
        "isotopes": "¹⁹¹Ir, ¹⁹³Ir",
        "fact": "Iridium is extremely corrosion-resistant and is found in meteorites in higher concentrations than in Earth's crust."
    },
    {
        "atomicNumber": 78,
        "symbol": "Pt",
        "name": "Platinum",
        "atomicMass": "195.08",
        "category": "transition-metal",
        "group": 10,
        "period": 6,
        "x": 10,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d9 6s1",
        "discovered": "1735",
        "discoveredBy": "Antonio de Ulloa",
        "isotopes": "¹⁹⁰Pt, ¹⁹²Pt, ¹⁹⁴Pt, ¹⁹⁵Pt, ¹⁹⁶Pt, ¹⁹⁸Pt",
        "fact": "Platinum is so rare that all the platinum ever mined would fit in an average-sized living room."
    },
    {
        "atomicNumber": 79,
        "symbol": "Au",
        "name": "Gold",
        "atomicMass": "196.97",
        "category": "transition-metal",
        "group": 11,
        "period": 6,
        "x": 11,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d10 6s1",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "¹⁹⁷Au (only stable isotope)",
        "fact": "Gold is so malleable that a single ounce can be beaten into a sheet covering 100 square feet."
    },
    {
        "atomicNumber": 80,
        "symbol": "Hg",
        "name": "Mercury",
        "atomicMass": "200.59",
        "category": "transition-metal",
        "group": 12,
        "period": 6,
        "x": 12,
        "y": 6,
        "phase": "Liquid",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "¹⁹⁶Hg, ¹⁹⁸Hg, ¹⁹⁹Hg, ²⁰⁰Hg, ²⁰¹Hg, ²⁰²Hg, ²⁰⁴Hg",
        "fact": "Mercury is the only metal that is liquid at standard temperature and pressure."
    },
    {
        "atomicNumber": 81,
        "symbol": "Tl",
        "name": "Thallium",
        "atomicMass": "204.38",
        "category": "post-transition-metal",
        "group": 13,
        "period": 6,
        "x": 13,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p1",
        "discovered": "1861",
        "discoveredBy": "William Crookes",
        "isotopes": "²⁰³Tl, ²⁰⁵Tl",
        "fact": "Thallium is highly toxic and was once used in rat poison and insecticides."
    },
    {
        "atomicNumber": 82,
        "symbol": "Pb",
        "name": "Lead",
        "atomicMass": "207.2",
        "category": "post-transition-metal",
        "group": 14,
        "period": 6,
        "x": 14,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p2",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "²⁰⁴Pb, ²⁰⁶Pb, ²⁰⁷Pb, ²⁰⁸Pb",
        "fact": "Lead is heavy, soft, and toxic; it was widely used in pipes and paints."
    },
    {
        "atomicNumber": 83,
        "symbol": "Bi",
        "name": "Bismuth",
        "atomicMass": "208.98",
        "category": "post-transition-metal",
        "group": 15,
        "period": 6,
        "x": 15,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p3",
        "discovered": "Ancient",
        "discoveredBy": "Unknown",
        "isotopes": "²⁰⁹Bi",
        "fact": "Bismuth is the most naturally diamagnetic element and is used in cosmetics and medicines."
    },
    {
        "atomicNumber": 84,
        "symbol": "Po",
        "name": "Polonium",
        "atomicMass": "(209)",
        "category": "post-transition-metal",
        "group": 16,
        "period": 6,
        "x": 16,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p4",
        "discovered": "1898",
        "discoveredBy": "Marie Curie, Pierre Curie",
        "isotopes": "²⁰⁹Po (no stable isotopes)",
        "fact": "Polonium is highly radioactive and was discovered by Marie Curie."
    },
    {
        "atomicNumber": 85,
        "symbol": "At",
        "name": "Astatine",
        "atomicMass": "(210)",
        "category": "halogen",
        "group": 17,
        "period": 6,
        "x": 17,
        "y": 6,
        "phase": "Solid",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p5",
        "discovered": "1940",
        "discoveredBy": "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè",
        "isotopes": "²¹⁰At (no stable isotopes)",
        "fact": "Astatine is the rarest naturally occurring halogen."
    },
    {
        "atomicNumber": 86,
        "symbol": "Rn",
        "name": "Radon",
        "atomicMass": "(222)",
        "category": "noble-gas",
        "group": 18,
        "period": 6,
        "x": 18,
        "y": 6,
        "phase": "Gas",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p6",
        "discovered": "1899",
        "discoveredBy": "Friedrich Ernst Dorn",
        "isotopes": "²²²Rn (no stable isotopes)",
        "fact": "Radon is a radioactive gas that can accumulate in homes and is a health hazard."
    },
    {
        "atomicNumber": 87,
        "symbol": "Fr",
        "name": "Francium",
        "atomicMass": "(223)",
        "category": "alkali-metal",
        "group": 1,
        "period": 7,
        "x": 1,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 7s1",
        "discovered": "1939",
        "discoveredBy": "Marguerite Perey",
        "isotopes": "²²³Fr (no stable isotopes)",
        "fact": "Francium is extremely rare and highly radioactive."
    },
    {
        "atomicNumber": 88,
        "symbol": "Ra",
        "name": "Radium",
        "atomicMass": "(226)",
        "category": "alkaline-earth-metal",
        "group": 2,
        "period": 7,
        "x": 2,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 7s2",
        "discovered": "1898",
        "discoveredBy": "Marie Curie, Pierre Curie",
        "isotopes": "²²⁶Ra (no stable isotopes)",
        "fact": "Radium was once used in luminous paints for watches and dials."
    },
    {
        "atomicNumber": 89,
        "symbol": "Ac",
        "name": "Actinium",
        "atomicMass": "(227)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 3,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 6d1 7s2",
        "discovered": "1899",
        "discoveredBy": "Friedrich Oskar Giesel",
        "isotopes": "²²⁷Ac (no stable isotopes)",
        "fact": "Actinium glows faintly in the dark due to its radioactivity."
    },
    {
        "atomicNumber": 90,
        "symbol": "Th",
        "name": "Thorium",
        "atomicMass": "232.04",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 4,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 6d2 7s2",
        "discovered": "1828",
        "discoveredBy": "Jöns Jacob Berzelius",
        "isotopes": "²³²Th",
        "fact": "Thorium is used in gas mantles and has potential as a nuclear fuel."
    },
    {
        "atomicNumber": 91,
        "symbol": "Pa",
        "name": "Protactinium",
        "atomicMass": "231.04",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 5,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f2 6d1 7s2",
        "discovered": "1913",
        "discoveredBy": "Oswald Helmuth Göhring, Kasimir Fajans",
        "isotopes": "²³¹Pa",
        "fact": "Protactinium is one of the rarest and most expensive naturally occurring elements."
    },
    {
        "atomicNumber": 92,
        "symbol": "U",
        "name": "Uranium",
        "atomicMass": "238.03",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 6,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f3 6d1 7s2",
        "discovered": "1789",
        "discoveredBy": "Martin Heinrich Klaproth",
        "isotopes": "²³⁸U, ²³⁵U, ²³⁴U",
        "fact": "Uranium is used as fuel in nuclear reactors and weapons."
    },
    {
        "atomicNumber": 93,
        "symbol": "Np",
        "name": "Neptunium",
        "atomicMass": "(237)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 7,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f4 6d1 7s2",
        "discovered": "1940",
        "discoveredBy": "Edwin McMillan, Philip H. Abelson",
        "isotopes": "²³⁷Np (no stable isotopes)",
        "fact": "Neptunium was the first transuranium element to be discovered."
    },
    {
        "atomicNumber": 94,
        "symbol": "Pu",
        "name": "Plutonium",
        "atomicMass": "(244)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 8,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f6 7s2",
        "discovered": "1940",
        "discoveredBy": "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur C. Wahl",
        "isotopes": "²³⁹Pu, ²⁴⁰Pu, ²⁴¹Pu, ²⁴⁴Pu",
        "fact": "Plutonium is used in nuclear weapons and as a fuel in nuclear reactors."
    },
    {
        "atomicNumber": 95,
        "symbol": "Am",
        "name": "Americium",
        "atomicMass": "(243)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 9,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f7 7s2",
        "discovered": "1944",
        "discoveredBy": "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, Albert Ghiorso",
        "isotopes": "²⁴¹Am, ²⁴³Am",
        "fact": "Americium is used in smoke detectors."
    },
    {
        "atomicNumber": 96,
        "symbol": "Cm",
        "name": "Curium",
        "atomicMass": "(247)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 10,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f7 6d1 7s2",
        "discovered": "1944",
        "discoveredBy": "Glenn T. Seaborg, Ralph A. James, Albert Ghiorso",
        "isotopes": "²⁴⁴Cm, ²⁴⁶Cm, ²⁴⁸Cm",
        "fact": "Curium is named after Marie and Pierre Curie."
    },
    {
        "atomicNumber": 97,
        "symbol": "Bk",
        "name": "Berkelium",
        "atomicMass": "(247)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 11,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f9 7s2",
        "discovered": "1949",
        "discoveredBy": "Glenn T. Seaborg, Stanley G. Thompson, Albert Ghiorso",
        "isotopes": "²⁴⁷Bk",
        "fact": "Berkelium is named after the city of Berkeley, California."
    },
    {
        "atomicNumber": 98,
        "symbol": "Cf",
        "name": "Californium",
        "atomicMass": "(251)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 12,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f10 7s2",
        "discovered": "1950",
        "discoveredBy": "Stanley G. Thompson, Kenneth Street Jr., Albert Ghiorso, Glenn T. Seaborg",
        "isotopes": "²⁴⁹Cf, ²⁵¹Cf",
        "fact": "Californium is used in neutron moisture gauges and as a neutron source."
    },
    {
        "atomicNumber": 99,
        "symbol": "Es",
        "name": "Einsteinium",
        "atomicMass": "(252)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 13,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f11 7s2",
        "discovered": "1952",
        "discoveredBy": "Albert Ghiorso, Stanley G. Thompson, Glenn T. Seaborg",
        "isotopes": "²⁵³Es",
        "fact": "Einsteinium is named after Albert Einstein."
    },
    {
        "atomicNumber": 100,
        "symbol": "Fm",
        "name": "Fermium",
        "atomicMass": "(257)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 14,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f12 7s2",
        "discovered": "1952",
        "discoveredBy": "Albert Ghiorso, Stanley G. Thompson, Glenn T. Seaborg",
        "isotopes": "²⁵⁷Fm",
        "fact": "Fermium was discovered in the debris of the first hydrogen bomb explosion."
    },
    {
        "atomicNumber": 101,
        "symbol": "Md",
        "name": "Mendelevium",
        "atomicMass": "(258)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 15,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f13 7s2",
        "discovered": "1955",
        "discoveredBy": "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin, Stanley G. Thompson",
        "isotopes": "²⁵⁸Md",
        "fact": "Mendelevium is named after Dmitri Mendeleev, creator of the periodic table."
    },
    {
        "atomicNumber": 102,
        "symbol": "No",
        "name": "Nobelium",
        "atomicMass": "(259)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 16,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 7s2",
        "discovered": "1958",
        "discoveredBy": "Joint Institute for Nuclear Research",
        "isotopes": "²⁵⁹No",
        "fact": "Nobelium is named after Alfred Nobel, inventor of dynamite."
    },
    {
        "atomicNumber": 103,
        "symbol": "Lr",
        "name": "Lawrencium",
        "atomicMass": "(266)",
        "category": "actinide",
        "group": null,
        "period": 7,
        "x": 17,
        "y": 10,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 7s2 7p1",
        "discovered": "1961",
        "discoveredBy": "Albert Ghiorso, Torbjørn Sikkeland, Almon E. Larsh, Robert M. Latimer",
        "isotopes": "²⁶²Lr, ²⁶⁶Lr",
        "fact": "Lawrencium is named after Ernest O. Lawrence, inventor of the cyclotron."
    },
    {
        "atomicNumber": 104,
        "symbol": "Rf",
        "name": "Rutherfordium",
        "atomicMass": "(267)",
        "category": "transition-metal",
        "group": 4,
        "period": 7,
        "x": 4,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d2 7s2",
        "discovered": "1964",
        "discoveredBy": "Joint Institute for Nuclear Research",
        "isotopes": "²⁶⁷Rf",
        "fact": "Rutherfordium is named after physicist Ernest Rutherford."
    },
    {
        "atomicNumber": 105,
        "symbol": "Db",
        "name": "Dubnium",
        "atomicMass": "(270)",
        "category": "transition-metal",
        "group": 5,
        "period": 7,
        "x": 5,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d3 7s2",
        "discovered": "1967",
        "discoveredBy": "Joint Institute for Nuclear Research and Lawrence Berkeley National Laboratory",
        "isotopes": "²⁷⁰Db",
        "fact": "Dubnium is named after the town of Dubna in Russia."
    },
    {
        "atomicNumber": 106,
        "symbol": "Sg",
        "name": "Seaborgium",
        "atomicMass": "(271)",
        "category": "transition-metal",
        "group": 6,
        "period": 7,
        "x": 6,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d4 7s2",
        "discovered": "1974",
        "discoveredBy": "Lawrence Berkeley National Laboratory",
        "isotopes": "²⁷¹Sg",
        "fact": "Seaborgium is named after Glenn T. Seaborg, a Nobel laureate in chemistry."
    },
    {
        "atomicNumber": 107,
        "symbol": "Bh",
        "name": "Bohrium",
        "atomicMass": "(270)",
        "category": "transition-metal",
        "group": 7,
        "period": 7,
        "x": 7,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d5 7s2",
        "discovered": "1981",
        "discoveredBy": "Gesellschaft für Schwerionenforschung",
        "isotopes": "²⁷⁰Bh",
        "fact": "Bohrium is named after Danish physicist Niels Bohr."
    },
    {
        "atomicNumber": 108,
        "symbol": "Hs",
        "name": "Hassium",
        "atomicMass": "(277)",
        "category": "transition-metal",
        "group": 8,
        "period": 7,
        "x": 8,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d6 7s2",
        "discovered": "1984",
        "discoveredBy": "Gesellschaft für Schwerionenforschung",
        "isotopes": "²⁷⁷Hs",
        "fact": "Hassium is named after the German state of Hesse."
    },
    {
        "atomicNumber": 109,
        "symbol": "Mt",
        "name": "Meitnerium",
        "atomicMass": "(278)",
        "category": "transition-metal",
        "group": 9,
        "period": 7,
        "x": 9,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d7 7s2",
        "discovered": "1982",
        "discoveredBy": "Gesellschaft für Schwerionenforschung",
        "isotopes": "²⁷⁸Mt",
        "fact": "Meitnerium is named after physicist Lise Meitner."
    },
    {
        "atomicNumber": 110,
        "symbol": "Ds",
        "name": "Darmstadtium",
        "atomicMass": "(281)",
        "category": "transition-metal",
        "group": 10,
        "period": 7,
        "x": 10,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d9 7s1",
        "discovered": "1994",
        "discoveredBy": "Gesellschaft für Schwerionenforschung",
        "isotopes": "²⁸¹Ds",
        "fact": "Darmstadtium is named after the city of Darmstadt, Germany."
    },
    {
        "atomicNumber": 111,
        "symbol": "Rg",
        "name": "Roentgenium",
        "atomicMass": "(282)",
        "category": "transition-metal",
        "group": 11,
        "period": 7,
        "x": 11,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d10 7s1",
        "discovered": "1994",
        "discoveredBy": "Gesellschaft für Schwerionenforschung",
        "isotopes": "²⁸²Rg",
        "fact": "Roentgenium is named after Wilhelm Röntgen, discoverer of X-rays."
    },
    {
        "atomicNumber": 112,
        "symbol": "Cn",
        "name": "Copernicium",
        "atomicMass": "(285)",
        "category": "transition-metal",
        "group": 12,
        "period": 7,
        "x": 12,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2",
        "discovered": "1996",
        "discoveredBy": "Gesellschaft für Schwerionenforschung",
        "isotopes": "²⁸⁵Cn",
        "fact": "Copernicium is named after astronomer Nicolaus Copernicus."
    },
    {
        "atomicNumber": 113,
        "symbol": "Nh",
        "name": "Nihonium",
        "atomicMass": "(286)",
        "category": "post-transition-metal",
        "group": 13,
        "period": 7,
        "x": 13,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p1",
        "discovered": "2004",
        "discoveredBy": "RIKEN",
        "isotopes": "²⁸⁶Nh",
        "fact": "Nihonium is named after Japan (Nihon in Japanese)."
    },
    {
        "atomicNumber": 114,
        "symbol": "Fl",
        "name": "Flerovium",
        "atomicMass": "(289)",
        "category": "post-transition-metal",
        "group": 14,
        "period": 7,
        "x": 14,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p2",
        "discovered": "1998",
        "discoveredBy": "Joint Institute for Nuclear Research and Lawrence Livermore National Laboratory",
        "isotopes": "²⁸⁹Fl",
        "fact": "Flerovium is named after the Flerov Laboratory of Nuclear Reactions."
    },
    {
        "atomicNumber": 115,
        "symbol": "Mc",
        "name": "Moscovium",
        "atomicMass": "(290)",
        "category": "post-transition-metal",
        "group": 15,
        "period": 7,
        "x": 15,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p3",
        "discovered": "2003",
        "discoveredBy": "Joint Institute for Nuclear Research and Lawrence Livermore National Laboratory",
        "isotopes": "²⁹⁰Mc",
        "fact": "Moscovium is named after Moscow Oblast, Russia."
    },
    {
        "atomicNumber": 116,
        "symbol": "Lv",
        "name": "Livermorium",
        "atomicMass": "(293)",
        "category": "post-transition-metal",
        "group": 16,
        "period": 7,
        "x": 16,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p4",
        "discovered": "2000",
        "discoveredBy": "Joint Institute for Nuclear Research and Lawrence Livermore National Laboratory",
        "isotopes": "²⁹³Lv",
        "fact": "Livermorium is named after Lawrence Livermore National Laboratory."
    },
    {
        "atomicNumber": 117,
        "symbol": "Ts",
        "name": "Tennessine",
        "atomicMass": "(294)",
        "category": "halogen",
        "group": 17,
        "period": 7,
        "x": 17,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p5",
        "discovered": "2010",
        "discoveredBy": "Joint Institute for Nuclear Research, Oak Ridge National Laboratory, Vanderbilt University, Lawrence Livermore National Laboratory",
        "isotopes": "²⁹⁴Ts",
        "fact": "Tennessine is named after the state of Tennessee, USA."
    },
    {
        "atomicNumber": 118,
        "symbol": "Og",
        "name": "Oganesson",
        "atomicMass": "(294)",
        "category": "noble-gas",
        "group": 18,
        "period": 7,
        "x": 18,
        "y": 7,
        "phase": "Solid",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p6",
        "discovered": "2002",
        "discoveredBy": "Joint Institute for Nuclear Research and Lawrence Livermore National Laboratory",
        "isotopes": "²⁹⁴Og",
        "fact": "Oganesson is named after Russian physicist Yuri Oganessian."
    }
];




elements.forEach(e => console.log(e.symbol, e.x, e.y)); // Find max x and y
const maxX = Math.max(...elements.map(e => e.x));
const maxY = Math.max(...elements.map(e => e.y));
// Create grid
const grid = Array.from({ length: maxY }, () => Array(maxX).fill(null));

export { elements };